/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my_package;

import javax.swing.JOptionPane;
import api.MemberController;
import models.Member;
import models.MemberSingleton;

/**
 *
 * @author AL AHLAWY
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login0
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        passwordTextField2 = new javax.swing.JPasswordField();
        loginBtn2 = new javax.swing.JButton();
        clearBtn2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        createAccountBtn2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(243, 238, 234));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(119, 107, 93));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Get Started");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(119, 107, 93));
        jLabel11.setText("Email :");

        emailTextField2.setBackground(new java.awt.Color(176, 166, 149));
        emailTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailTextField2.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emailTextField2.setName(""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(119, 107, 93));
        jLabel12.setText("Password :");

        passwordTextField2.setBackground(new java.awt.Color(176, 166, 149));
        passwordTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordTextField2.setForeground(new java.awt.Color(255, 255, 255));

        loginBtn2.setBackground(new java.awt.Color(119, 107, 93));
        loginBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn2.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn2.setText("LOGIN");
        loginBtn2.setBorder(null);
        loginBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtn2ActionPerformed(evt);
            }
        });

        clearBtn2.setBackground(new java.awt.Color(243, 238, 234));
        clearBtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn2.setForeground(new java.awt.Color(119, 107, 93));
        clearBtn2.setText("CLEAR");
        clearBtn2.setToolTipText("");
        clearBtn2.setBorder(null);
        clearBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn2.setDefaultCapable(false);
        clearBtn2.setFocusPainted(false);
        clearBtn2.setFocusable(false);
        clearBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(119, 107, 93));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Didn't have account?");

        createAccountBtn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createAccountBtn2.setForeground(new java.awt.Color(119, 107, 93));
        createAccountBtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAccountBtn2.setText("Create Account");
        createAccountBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountBtn2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addComponent(passwordTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createAccountBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailTextField2, passwordTextField2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(loginBtn2)
                .addGap(18, 18, 18)
                .addComponent(clearBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccountBtn2)
                .addGap(23, 23, 23))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailTextField2, passwordTextField2});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearBtn2, loginBtn2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn2ActionPerformed
        if(emailTextField2.getText().trim().isEmpty())
           JOptionPane.showMessageDialog(null, "The email is not invalid", "Validation Error", JOptionPane.ERROR_MESSAGE);
        else if(passwordTextField2.getText().trim().isEmpty())
            JOptionPane.showMessageDialog(null, "The password is empty", "Validation Error", JOptionPane.ERROR_MESSAGE);
        else{
            Member m = MemberController.getMemberByEmail(emailTextField2.getText());
            if (m == null) {
                return;
            }
            if (m.password.equals(new String(passwordTextField2.getPassword()))) {
                MemberSingleton.getInstance().setMember(m);
                new landingPage().show();
                dispose();
                System.out.println(MemberSingleton.getInstance().getMember().toString());
            } else {
                JOptionPane.showMessageDialog(this, "Password is not correct", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_loginBtn2ActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        emailTextField2.setText("");
        passwordTextField2.setText("");
    }//GEN-LAST:event_clearBtn2ActionPerformed

    private void createAccountBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountBtn2MouseClicked
        sign_up sign = new sign_up();
        this.hide();
        sign.show();
    }//GEN-LAST:event_createAccountBtn2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JLabel createAccountBtn;
    private javax.swing.JLabel createAccountBtn1;
    private javax.swing.JLabel createAccountBtn2;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginBtn1;
    private javax.swing.JButton loginBtn2;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPasswordField passwordTextField1;
    private javax.swing.JPasswordField passwordTextField2;
    // End of variables declaration//GEN-END:variables
}
